### ISSUE TITLE
Subscriptions are broken

### ISSUE THREAD

**Issue by dandago** [apollographql/starwars-server#19]
If you start a subscription and apply a mutation, you never get notified because of a bug in the pubsub code. To reproduce:

```
subscription {
  reviewAdded {
    episode
    stars
    commentary
  }
}
```

Then:

```
mutation {
  createReview(episode: EMPIRE, review: {
    stars: 3,
    commentary: "Some text"
  }) {
    episode
    stars
    commentary
  }
}
```

I am going to submit a PR to fix this shortly.

**Comment by calvincestari** [comment]
Closing this issue as the repo is being archived.
