### ISSUE TITLE
Add queries to return the full list of characters, humans, droids and starships

### ISSUE THREAD

**Issue by dlavrenuek** [apollographql/starwars-server#22]
Currently the `search` query with empty `text` is the only way to return the data and there is no way to filter specific object types like `Human`, `Droid`, etc. There should be a way to retrieve a full list of characters, humans, droids and starships by adding respective queries.

- [x] Add `characters` query that returns all characters
- [x] Add `humans` query that returns all humans
- [x] Add `droids` query that returns all droids
- [x] Add `starships` query that returns all starships

**Comment by calvincestari** [comment]
Closing this issue as the repo is being archived.
